name: Feat 请求
description: 提交新的 NapCat 功能或改进建议
title: '[FEAT] '
labels: enhancement
body:
  - type: markdown
    attributes:
      value: |
        欢迎来到 NapCat 的 Issue Tracker！请填写以下表格来提交功能请求。
        在提交新的功能请求前，请确保您：
        * 已经搜索了现有的 issues，并且没有找到类似的建议
        * 不与现有的某一 issue 重复
  - type: input
    id: system-version
    attributes:
      label: 系统版本
      description: 运行 QQNT 的系统版本
      placeholder: Windows 11 24H2
    validations:
      required: true
  - type: input
    id: qqnt-version
    attributes:
      label: QQNT 版本
      description: 可在 QQNT 的「关于」的设置页中找到
      placeholder: 9.9.16-29927
    validations:
      required: true
  - type: input
    id: napcat-version
    attributes:
      label: NapCat 版本
      description: 可在 WebUI 的「系统信息」页中找到
      placeholder: 1.0.0
    validations:
      required: true
  - type: textarea
    id: feature-description
    attributes:
      label: 功能描述
      description: 请详细描述你希望添加的功能或改进
    validations:
      required: true
  - type: textarea
    id: feature-reason
    attributes:
      label: 需求背景与理由
      description: 请说明为什么需要这个功能，解决了什么问题
    validations:
      required: true
  - type: textarea
    id: feature-expected
    attributes:
      label: 期望的实现方式或效果
      description: 请描述你期望的功能实现方式或最终效果
  - type: textarea
    id: other-info
    attributes:
      label: 其他补充信息
      description: 你还想补充什么？
