import { WrapperSessionInitConfig } from './sessionConfig';
import { NodeIDependsAdapter, NodeIDispatcherAdapter, NodeIGlobalAdapter } from './adapters';
import { NodeIKernelSessionListener, NodeIKernelMsgListener, NodeIKernelLoginListener, NodeIKernelBuddyListener, NodeIKernelGroupListener, NodeIKernelProfileListener } from './listeners';
import { NodeIKernelLoginService, NodeIKernelMsgService, NodeIKernelBuddyService, NodeIKernelGroupService, NodeIKernelProfileService, NodeIKernelProfileLikeService, NodeIKernelTicketService, NodeIKernelTipOffService, NodeIKernelRichMediaService, NodeIKernelAvatarService } from './services';
import { NodeIKernelStorageCleanService } from './services/NodeIKernelStorageCleanService';
import { NodeIKernelRobotService } from './services/NodeIKernelRobotService';
import { NodeIKernelNodeMiscService } from './services/NodeIKernelNodeMiscService';
import { NodeIKernelUixConvertService } from './services/NodeIKernelUixConvertService';
import { NodeIKernelMsgBackupService } from './services/NodeIKernelMsgBackupService';
import { NodeIKernelAlbumService } from './services/NodeIKernelAlbumService';
import { NodeIKernelTianShuService } from './services/NodeIKernelTianShuService';
import { NodeIKernelUnitedConfigService } from './services/NodeIKernelUnitedConfigService';
import { NodeIKernelSearchService } from './services/NodeIKernelSearchService';
import { NodeIKernelCollectionService } from './services/NodeIKernelCollectionService';
export interface NodeQQNTWrapperUtil {
    new (): NodeQQNTWrapperUtil;
    getNTUserDataInfoConfig(): string;
    emptyWorkingSet(n: number): void;
    getSsoCmdOfOidbReq(arg1: number, arg2: number): unknown;
    getSsoBufferOfOidbReq(...args: unknown[]): unknown;
    getOidbRspInfo(arg: string): unknown;
    getFileSize(path: string): Promise<number>;
    genFileMd5Buf(arg: string): unknown;
    genFileMd5Hex(path: string): unknown;
    genFileShaBuf(path: string): unknown;
    genFileCumulateSha1(path: string): unknown;
    genFileShaHex(path: string): unknown;
    fileIsExist(path: string): unknown;
    startTrace(path: string): unknown;
    copyFile(src: string, dst: string): unknown;
    genFileShaAndMd5Hex(path: string, unknown: number): unknown;
    setTraceInfo(unknown: Object): unknown;
    encodeOffLine(unknown: Object): unknown;
    decodeOffLine(arg: string): unknown;
    DecoderRecentInfo(arg: string): unknown;
    getPinyin(arg0: string, arg1: boolean): unknown;
    matchInPinyin(arg0: any[], arg1: string): unknown;
    makeDirByPath(arg0: string): unknown;
    emptyWorkingSet(arg0: number): unknown;
    runProcess(arg0: string, arg1: boolean): unknown;
    runProcessArgs(arg0: string, arg1: {
        [key: string]: string;
    }, arg2: boolean): unknown;
    calcThumbSize(arg0: number, arg1: number, arg2: Object): unknown;
    fullWordToHalfWord(arg0: string): unknown;
    getNTUserDataInfoConfig(): unknown;
    pathIsReadableAndWriteable(path: string): unknown;
    resetUserDataSavePathToDocument(): unknown;
    getSoBuildInfo(): any;
    registerCountInstruments(arg0: string, arg1: string[], arg2: number, arg3: number): unknown;
    registerValueInstruments(arg0: string, arg1: string[], arg2: number, arg3: number): unknown;
    registerValueInstrumentsWithBoundary(arg0: string, arg1: unknown, arg2: unknown, arg3: number, arg4: number): unknown;
    reportCountIndicators(arg0: string, arg1: Map<unknown, unknown>, arg2: string, arg3: number, arg4: boolean): unknown;
    reportValueIndicators(arg0: string, arg1: Map<unknown, unknown>, arg2: string, arg3: boolean, arg4: number): unknown;
    checkNewUserDataSaveDirAvailable(arg0: string): unknown;
    copyUserData(arg0: string, arg1: string): Promise<any>;
    setUserDataSaveDirectory(arg0: string): Promise<any>;
    hasOtherRunningQQProcess(): boolean;
    quitAllRunningQQProcess(arg: boolean): unknown;
    checkNvidiaConfig(): unknown;
    repairNvidiaConfig(): unknown;
    getNvidiaDriverVersion(): unknown;
    isNull(): unknown;
}
export interface NodeIQQNTWrapperSession {
    new (): NodeIQQNTWrapperSession;
    init(wrapperSessionInitConfig: WrapperSessionInitConfig, nodeIDependsAdapter: NodeIDependsAdapter, nodeIDispatcherAdapter: NodeIDispatcherAdapter, nodeIKernelSessionListener: NodeIKernelSessionListener): void;
    startNT(n: 0): void;
    startNT(): void;
    getMsgService(): NodeIKernelMsgService;
    getProfileService(): NodeIKernelProfileService;
    getProfileLikeService(): NodeIKernelProfileLikeService;
    getGroupService(): NodeIKernelGroupService;
    getStorageCleanService(): NodeIKernelStorageCleanService;
    getBuddyService(): NodeIKernelBuddyService;
    getRobotService(): NodeIKernelRobotService;
    getTicketService(): NodeIKernelTicketService;
    getTipOffService(): NodeIKernelTipOffService;
    getNodeMiscService(): NodeIKernelNodeMiscService;
    getRichMediaService(): NodeIKernelRichMediaService;
    getMsgBackupService(): NodeIKernelMsgBackupService;
    getAlbumService(): NodeIKernelAlbumService;
    getTianShuService(): NodeIKernelTianShuService;
    getUnitedConfigService(): NodeIKernelUnitedConfigService;
    getSearchService(): NodeIKernelSearchService;
    getDirectSessionService(): unknown;
    getRDeliveryService(): unknown;
    getAvatarService(): NodeIKernelAvatarService;
    getFeedChannelService(): unknown;
    getYellowFaceService(): unknown;
    getCollectionService(): NodeIKernelCollectionService;
    getSettingService(): unknown;
    getQiDianService(): unknown;
    getFileAssistantService(): unknown;
    getGuildService(): unknown;
    getSkinService(): unknown;
    getTestPerformanceService(): unknown;
    getQQPlayService(): unknown;
    getDbToolsService(): unknown;
    getUixConvertService(): NodeIKernelUixConvertService;
    getOnlineStatusService(): unknown;
    getRemotingService(): unknown;
    getGroupTabService(): unknown;
    getGroupSchoolService(): unknown;
    getLiteBusinessService(): unknown;
    getGuildMsgService(): unknown;
    getLockService(): unknown;
    getMSFService(): unknown;
    getGuildHotUpdateService(): unknown;
    getAVSDKService(): unknown;
    getRecentContactService(): unknown;
    getConfigMgrService(): unknown;
}
export interface EnginInitDesktopConfig {
    base_path_prefix: string;
    platform_type: 3;
    app_type: 4;
    app_version: string;
    os_version: string;
    use_xlog: true;
    qua: string;
    global_path_config: {
        desktopGlobalPath: string;
    };
    thumb_config: {
        maxSide: 324;
        minSide: 48;
        longLimit: 6;
        density: 2;
    };
}
export interface NodeIQQNTWrapperEngine {
    new (): NodeIQQNTWrapperEngine;
    initWithDeskTopConfig(config: EnginInitDesktopConfig, nodeIGlobalAdapter: NodeIGlobalAdapter): void;
}
export interface WrapperNodeApi {
    [key: string]: any;
    NodeIKernelBuddyListener: NodeIKernelBuddyListener;
    NodeIKernelGroupListener: NodeIKernelGroupListener;
    NodeQQNTWrapperUtil: NodeQQNTWrapperUtil;
    NodeIQQNTWrapperSession: NodeIQQNTWrapperSession;
    NodeIKernelMsgListener: NodeIKernelMsgListener;
    NodeIQQNTWrapperEngine: NodeIQQNTWrapperEngine;
    NodeIGlobalAdapter: NodeIGlobalAdapter;
    NodeIDependsAdapter: NodeIDependsAdapter;
    NodeIDispatcherAdapter: NodeIDispatcherAdapter;
    NodeIKernelSessionListener: NodeIKernelSessionListener;
    NodeIKernelLoginService: NodeIKernelLoginService;
    NodeIKernelLoginListener: NodeIKernelLoginListener;
    NodeIKernelProfileService: NodeIKernelProfileService;
    NodeIKernelProfileListener: NodeIKernelProfileListener;
}
declare const QQWrapper: WrapperNodeApi;
export default QQWrapper;
