import { Peer } from "../entities";
export interface NodeIKernelRecentContactService {
    setGuildDisplayStatus(...args: unknown[]): unknown;
    setContactListTop(...args: unknown[]): unknown;
    updateRecentContactExtBufForUI(...args: unknown[]): unknown;
    upsertRecentContactManually(...args: unknown[]): unknown;
    enterOrExitMsgList(...args: unknown[]): unknown;
    getRecentContactListSnapShot(...args: unknown[]): unknown;
    clearMsgUnreadCount(...args: unknown[]): unknown;
    getRecentContactListSyncLimit(count: number): unknown;
    jumpToSpecifyRecentContact(...args: unknown[]): unknown;
    fetchAndSubscribeABatchOfRecentContact(...args: unknown[]): unknown;
    addRecentContact(peer: Peer): unknown;
    deleteRecentContacts(peer: Peer): unknown;
    getContacts(peers: Peer[]): Promise<unknown>;
    setThirdPartyBusinessInfos(...args: unknown[]): unknown;
    updateGameMsgConfigs(...args: unknown[]): unknown;
    removeKernelRecentContactListener(...args: unknown[]): unknown;
    addKernelRecentContactListener(...args: unknown[]): unknown;
    clearRecentContactsByChatType(...args: unknown[]): unknown;
    upInsertModule(...args: unknown[]): unknown;
    jumpToSpecifyRecentContactVer2(...args: unknown[]): unknown;
    deleteRecentContactsVer2(...args: unknown[]): unknown;
    getRecentContactList(): unknown;
    getMsgUnreadCount(): unknown;
    clearRecentContacts(): unknown;
    getServiceAssistantRecentContactInfos(): unknown;
    getRecentContactInfos(): unknown;
    getUnreadDetailsInfos(): unknown;
    cleanAllModule(): unknown;
    setAllGameMsgRead(): unknown;
    getRecentContactListSync(): unknown;
}
